CREATE OR REPLACE PACKAGE PLA01.PKG_SIMA_PERSONAL AS

FUNCTION VeficaPersonalExiste(pCODCIA PLNMAETRA.PTRCODCIA%TYPE,pCODSUC PLNMAETRA.PTRCODSUC%TYPE,pNroDni PLNMAETRA.PTRNROLE%TYPE)RETURN VARCHAR2;

/*FUNCTION InsertaPersonal(pCODCIA PLNMAETRA.PTRCODCIA%TYPE,pCODSUC PLNMAETRA.PTRCODSUC%TYPE, pCODTRA PLNMAETRA.PTRCODTRA%TYPE, pCODTIP PLNMAETRA.PTRCODTIP%TYPE,pTRANOM PLNMAETRA.PTRTRANOM%TYPE,
                        pTRAAPP PLNMAETRA.PTRTRAAPP%TYPE,pTRAAPM PLNMAETRA.PTRTRAAPM%TYPE,pESTCIV PLNMAETRA.PTRESTCIV%TYPE,pFECINI PLNMAETRA.PTRFECINI%TYPE,pFECNAC PLNMAETRA.PTRFECNAC%TYPE,
                        pGRAINS PLNMAETRA.PTRGRAINS%TYPE,pCODSEX PLNMAETRA.PTRCODSEX%TYPE,pDIRTRA PLNMAETRA.PTRDIRTRA%TYPE,pNROLE PLNMAETRA.PTRNROLE%TYPE,pNROLM PLNMAETRA.PTRNROLM%TYPE,
                        pNRORUC PLNMAETRA.PTRNRORUC%TYPE,pNROSSP PLNMAETRA.PTRNROSSP%TYPE,pNROAFP PLNMAETRA.PTRNROAFP%TYPE,pCODAFP PLNMAETRA.PTRCODAFP%TYPE,pFECING PLNMAETRA.PTRFECING%TYPE,
                        pFECRET PLNMAETRA.PTRFECRET%TYPE,pFLGEST PLNMAETRA.PTRFLGEST%TYPE,pCODNAC PLNMAETRA.PTRCODNAC%TYPE,pTIPREM PLNMAETRA.PTRTIPREM%TYPE,pTIPCON PLNMAETRA.PTRTIPCON%TYPE,
                        pCENCOS PLNMAETRA.PTRCENCOS%TYPE,pCODSEC PLNMAETRA.PTRCODSEC%TYPE,pPUESTO PLNMAETRA.PTRPUESTO%TYPE,pCODGEN PLNMAETRA.PTRCODGEN%TYPE,pBCOCTS PLNMAETRA.PTRBCOCTS%TYPE,
                        pMONCTS PLNMAETRA.PTRMONCTS%TYPE,pCODCTA PLNMAETRA.PTRCODCTA%TYPE,pTIPCTA PLNMAETRA.PTRTIPCTA%TYPE,pFLGMAR PLNMAETRA.PTRFLGMAR%TYPE,pMONPAG PLNMAETRA.PTRMONPAG%TYPE,
                        pBCODEP PLNMAETRA.PTRBCODEP%TYPE,pUBICOD PLNMAETRA.PTRUBICOD%TYPE,pCODANT PLNMAETRA.PTRCODANT%TYPE,pTIPDOC PLNMAETRA.PTRTIPDOC%TYPE,pNUMTEL PLNMAETRA.PTRNUMTEL%TYPE,
                        pTIPVIA PLNMAETRA.PTRTIPVIA%TYPE,pTIPZON PLNMAETRA.PTRTIPZON%TYPE,pNOMVIA PLNMAETRA.PTRNOMVIA%TYPE,pUBIDIS PLNMAETRA.PTRUBIDIS%TYPE,pUBIPRV PLNMAETRA.PTRUBIPRV%TYPE,
                        pUBIDEP PLNMAETRA.PTRUBIDEP%TYPE,pCTACTS PLNMAETRA.PTRCTACTS%TYPE,pMONDEP PLNMAETRA.PTRMONDEP%TYPE,pFLGDOM PLNMAETRA.PTRFLGDOM%TYPE,pSENATI PLNMAETRA.PTRSENATI%TYPE,
                        pCODPUE PLNMAETRA.PTRCODPUE%TYPE,pFINCON PLNMAETRA.PTRFINCON%TYPE,pSITTRA PLNMAETRA.PTRSITTRA%TYPE,pFLGDIS PLNMAETRA.PTRFLGDIS%TYPE,pEMAIL PLNMAETRA.PTREMAIL%TYPE,
                        pNUMCEL PLNMAETRA.PTRNUMCEL%TYPE,pMAILCO PLNMAETRA.PTRMAILCOR%TYPE,pUSRRED PLNMAETRA.PTRUSRRED%TYPE) RETURN VARCHAR2;*/
FUNCTION InsertaPersonal(pCODCIA VARCHAR2,pCODSUC VARCHAR2,pCODTRA VARCHAR2,pCODTIP VARCHAR2,pTRANOM VARCHAR2,pTRAAPP VARCHAR2,pTRAAPM VARCHAR2,pESTCIV VARCHAR2,
                         pFECINI VARCHAR2,pFECNAC VARCHAR2,pGRAINS VARCHAR2,pCODSEX VARCHAR2,pDIRTRA VARCHAR2, pNROLE VARCHAR2,pNROLM  VARCHAR2,pNRORUC VARCHAR2,
                         pNROSSP VARCHAR2,pNROAFP VARCHAR2,pCODAFP VARCHAR2,pFECING VARCHAR2,pFECRET VARCHAR2,pFLGEST VARCHAR2,pCODNAC VARCHAR2,pTIPREM VARCHAR2,pTIPCON VARCHAR2,
                         pCENCOS VARCHAR2,pCODSEC VARCHAR2,pPUESTO VARCHAR2,pCODGEN VARCHAR2,pBCOCTS VARCHAR2,pMONCTS VARCHAR2,pCODCTA VARCHAR2,pTIPCTA VARCHAR2,pFLGMAR VARCHAR2,
                         pMONPAG VARCHAR2,pBCODEP VARCHAR2,pUBICOD VARCHAR2,pCODANT VARCHAR2,pTIPDOC VARCHAR2,pNUMTEL VARCHAR2,pTIPVIA VARCHAR2,pTIPZON VARCHAR2,pNOMVIA VARCHAR2,
                         pUBIDIS VARCHAR2,pUBIPRV VARCHAR2,pUBIDEP VARCHAR2,pCTACTS VARCHAR2,pMONDEP VARCHAR2,pFLGDOM VARCHAR2,pSENATI VARCHAR2,pCODPUE VARCHAR2,pFINCON VARCHAR2,
                         pSITTRA VARCHAR2,pFLGDIS VARCHAR2,pEMAIL VARCHAR2, pNUMCEL VARCHAR2,pMAILCO VARCHAR2,pUSRRED VARCHAR2) RETURN VARCHAR2;                        
                        

 PROCEDURE spInsertaPersonal ( stPLNMAETRA PLNMAETRA%ROWTYPE, pCantInsert  OUT NUMBER);
 
 
 PROCEDURE spActualizaPersonal ( stPLNMAETRA PLNMAETRA%ROWTYPE, pCantAct  OUT NUMBER);



END;
/